basePath: /
definitions:
  models.Label:
    description: A tag or category that can be assigned to users
    properties:
      color:
        example: '#FF5733'
        type: string
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        format: uuid
        type: string
      name:
        example: admin
        type: string
    type: object
  models.Message:
    description: A message sent through the SSE stream
    properties:
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        format: uuid
        type: string
      text:
        example: Hello, world!
        type: string
      timestamp:
        example: "2023-01-01T12:00:00Z"
        format: date-time
        type: string
      user:
        $ref: '#/definitions/models.User'
    type: object
  models.User:
    description: User account information
    properties:
      email:
        type: string
      id:
        type: string
      labels:
        items:
          $ref: '#/definitions/models.Label'
        type: array
      nickname:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Server-Sent Events Gadget Backend API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: SSE Gadget API
  version: "1.0"
paths:
  /stream:
    get:
      consumes:
      - application/json
      description: Establishes an SSE connection and receives real-time updates
      produces:
      - text/event-stream
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Message'
            type: array
      summary: Subscribe to the SSE stream
      tags:
      - stream
schemes:
- http
swagger: "2.0"
